name: goprofile
dependencies:
    angular2: 'any'
    browser: 'any'
    bootstrap: 'any'
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
